// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSeWCfWwtrqCcv2iWiFhXjED-HavLyyA0',
    appId: '1:400802425980:web:bf4cc6a46342f4fbbf6df9',
    messagingSenderId: '400802425980',
    projectId: 'voltra-9011a',
    authDomain: 'voltra-9011a.firebaseapp.com',
    storageBucket: 'voltra-9011a.firebasestorage.app',
    measurementId: 'G-GQ5YJFHGS9',
    // [ADICIONADO] URL do Realtime Database
    databaseURL: 'https://voltra-9011a-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASMoPg2LWIAS7C6Z6SQbOemoHdTdjNG80',
    appId: '1:400802425980:android:e8a7f5afd6ff9013bf6df9',
    messagingSenderId: '400802425980',
    projectId: 'voltra-9011a',
    storageBucket: 'voltra-9011a.firebasestorage.app',
    // [ADICIONADO] URL do Realtime Database
    databaseURL: 'https://voltra-9011a-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq19H5Tls91Rr6Jm4en2IAeZoqcJXpKrI',
    appId: '1:400802425980:ios:348102d9c3defcf3bf6df9',
    messagingSenderId: '400802425980',
    projectId: 'voltra-9011a',
    storageBucket: 'voltra-9011a.firebasestorage.app',
    iosBundleId: 'com.example.locationTrackingApp',
    // [ADICIONADO] URL do Realtime Database
    databaseURL: 'https://voltra-9011a-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq19H5Tls91Rr6Jm4en2IAeZoqcJXpKrI',
    appId: '1:400802425980:ios:348102d9c3defcf3bf6df9',
    messagingSenderId: '400802425980',
    projectId: 'voltra-9011a',
    storageBucket: 'voltra-9011a.firebasestorage.app',
    iosBundleId: 'com.example.locationTrackingApp',
    // [ADICIONADO] URL do Realtime Database
    databaseURL: 'https://voltra-9011a-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSeWCfWwtrqCcv2iWiFhXjED-HavLyyA0',
    appId: '1:400802425980:web:34408f0998bf124fbf6df9',
    messagingSenderId: '400802425980',
    projectId: 'voltra-9011a',
    authDomain: 'voltra-9011a.firebaseapp.com',
    storageBucket: 'voltra-9011a.firebasestorage.app',
    measurementId: 'G-9S3C47MFE2',
    // [ADICIONADO] URL do Realtime Database
    databaseURL: 'https://voltra-9011a-default-rtdb.firebaseio.com',
  );
}